/**
 * AI Agent Context File Generator
 * ================================
 * Generates identical context files for all major AI coding CLI tools.
 * Each tool reads a different filename, but the content is the same.
 *
 * Supported tools:
 *   - Claude Code    → CLAUDE.md
 *   - OpenAI Codex   → AGENTS.md
 *   - Google Gemini   → GEMINI.md
 *   - Cursor          → .cursorrules
 *   - Generic         → CONTEXT.md
 *
 * SINGLE SOURCE OF TRUTH: generateAgentContextContent() produces the content.
 * writeAgentContextFiles() writes it to all target files.
 * To update what agents see, edit generateAgentContextContent() only.
 *
 * To add support for a new tool:
 *   1. Add the filename to AGENT_CONTEXT_FILES below
 *   2. Add it to .gitignore at the repo root
 *   3. Update the "DO NOT edit" section in the generated content
 *   That's it.
 */

import fs from 'fs'
import path from 'path'
import type { SceneState } from './scene-manager'

/**
 * All filenames that get the auto-generated agent context.
 * Add new AI tool filenames here — they all get identical content.
 */
const AGENT_CONTEXT_FILES = [
  'CLAUDE.md',      // Claude Code
  'AGENTS.md',      // OpenAI Codex CLI
  'GEMINI.md',      // Google Gemini CLI
  '.cursorrules',   // Cursor
  'CONTEXT.md',     // Generic / other tools
]

/**
 * Generate the agent context markdown content for a scene.
 * This is the single source of truth — all output files get this exact content.
 */
export function generateAgentContextContent(scene: SceneState): string {
  const widgetLines: string[] = []
  for (const entry of scene.meta.widgets) {
    const widget = scene.widgets.get(entry.id)
    if (!widget) continue
    const bounds = entry.bounds
    const boundsStr = bounds
      ? `at (${bounds.x}, ${bounds.y}) ${bounds.width}\u00d7${bounds.height}`
      : '(no bounds — positioned by layout.html)'
    const caps = widget.manifest.capabilities.length > 0
      ? widget.manifest.capabilities.join(', ')
      : 'none'
    widgetLines.push(
      `- **${widget.manifest.title}** (\`${entry.id}\`, type: ${widget.manifest.type}) ${boundsStr}\n  - Capabilities: ${caps}`,
    )
  }

  const widgetsSection = widgetLines.length > 0
    ? widgetLines.join('\n')
    : '_No widgets in this scene._'

  // Build dimension context section if the scene is part of a dimension
  let dimensionSection = ''
  if (scene.dimensionMeta) {
    const currentIndex = scene.dimensionMeta.scenes.indexOf(scene.slug)
    const sceneOrder = scene.dimensionMeta.scenes.join(' \u2192 ')
    dimensionSection = `
## Dimension: ${scene.dimensionMeta.title}
This scene is part of the "${scene.dimensionMeta.title}" dimension.
Scene order: ${sceneOrder}
Current position: ${currentIndex + 1} of ${scene.dimensionMeta.scenes.length}
`
  }

  // Layout mode section
  const viewport = scene.meta.viewport
  const viewportStr = viewport ? `${viewport.width}×${viewport.height}` : '1920×1080 (default)'
  let layoutSection = ''
  if (scene.layoutMode === 'layout') {
    layoutSection = `
## Layout Mode: CSS Layout
This scene uses **Layout mode** — widgets are positioned by \`layout.html\`, not by bounds in \`meta.json\`.
- Edit \`layout.html\` to change widget positioning (flexbox, grid, percentages, media queries)
- Use \`<dimensions-widget name="widget-type">\` to place widgets
- Widget bounds in meta.json are optional (CSS drives positioning)
- Drag/resize handles are disabled — edit layout.html directly
`
  } else {
    layoutSection = `
## Layout Mode: Canvas
This scene uses **Canvas mode** — widgets are positioned by \`bounds\` in \`meta.json\`.
**Viewport:** ${viewportStr} (design resolution)
**Scale modes:** Fit (scales to fill window) or Original (1:1 pixels, scroll if needed)
- Drag and resize widgets in edit mode
- To switch to CSS Layout mode, create a \`layout.html\` file in the scene folder
`
  }

  return `# Dimensions Scene Context

## Scene: ${scene.meta.title}
**ID:** ${scene.id}
**Slug:** ${scene.slug}
**Path:** ${scene.path}
${dimensionSection}${layoutSection}
### Active Widgets
${widgetsSection}

## IMPORTANT: What Files to Edit

**DO edit:**
- \`meta.json\` — scene title, theme (background, accent), viewport, widget layout/bounds
- \`layout.html\` — CSS layout template (Layout mode only; create to switch from Canvas to Layout)
- \`widgets/<name>/src/index.html\` — widget source code (HTML/JS/CSS)
- \`widgets/<name>/src/index.ts\` — widget TypeScript source
- \`widgets/<name>/src/widget.manifest.json\` — widget capabilities, inputs, outputs
- \`connections.json\` — dataflow wiring between widgets
- \`widgets/<portal>/portal-rules.json\` — CSS injection rules for webportals

**DO NOT edit:**
- \`.scene-runtime.html\` — AUTO-GENERATED, overwritten on every scene load and widget build
- \`widgets/<name>/dist/\` — AUTO-GENERATED by esbuild from src/
- \`CLAUDE.md\` / \`AGENTS.md\` / \`GEMINI.md\` / \`.cursorrules\` / \`CONTEXT.md\` — AUTO-GENERATED AI agent context files (all identical, one per tool)

### Changing the Scene Background
Every scene has a \`_background\` widget at \`widgets/_background/src/index.html\`.
This is a full-screen widget that renders behind all other widgets.

**To change the background:** Edit \`widgets/_background/src/index.html\`.
- Simple solid color: set \`body { background: #1a1a2e; }\`
- Gradient: \`body { background: linear-gradient(135deg, #0a0a0a, #1a1a2e); }\`
- Animation: use CSS \`@keyframes\` to cycle colors, pulse, etc.
- Canvas/WebGL: add a \`<canvas>\` and draw whatever you want
- Video: use a \`<video>\` element with \`object-fit: cover\`

The \`_background\` widget is a regular widget — it has full SDK access and can declare
any capabilities in its manifest (network, kv, theme, etc.). Use it for live data
backgrounds, interactive canvases, or anything else. It auto-reloads on save.

**Do NOT** edit \`.scene-runtime.html\` to change the background — it's auto-generated.

The \`theme.background\` in \`meta.json\` is a fallback color shown while widgets load.

## @dimensions/sdk API Reference

The SDK is automatically injected into every custom widget. Access it via \`window.sdk\`.

### Always Available (no capability required)
- \`sdk.scene.id()\` \u2192 string \u2014 Current scene ID
- \`sdk.scene.title()\` \u2192 string \u2014 Current scene title

### Key-Value Storage (requires "kv")
- \`sdk.kv.get(key)\` \u2192 Promise<any> \u2014 Get value by key
- \`sdk.kv.set(key, value)\` \u2192 Promise<void> \u2014 Set value (JSON serialized, max 10MB)
- \`sdk.kv.delete(key)\` \u2192 Promise<void> \u2014 Delete key
- \`sdk.kv.list(prefix?)\` \u2192 Promise<string[]> \u2014 List keys matching prefix

### Assets (requires "assets")
- \`sdk.assets.upload(file)\` \u2192 Promise<string> \u2014 Upload file, returns dimensions-asset:// URL
- \`sdk.assets.resolve(url)\` \u2192 Promise<string> \u2014 Validate and resolve asset URL
- \`sdk.assets.list()\` \u2192 Promise<AssetInfo[]> \u2014 List widget assets

### Network (requires "network")
- \`sdk.fetch(url, options?)\` \u2192 Promise<{status, headers, body}> \u2014 Proxied HTTP request (no CORS)
  - Manifest must declare \`allowedHosts\` array

### WebSocket (requires "websocket")
- \`sdk.ws.connect(url)\` \u2192 Promise<connectionId> \u2014 Open WebSocket connection
  - Manifest must declare \`allowedWsHosts\` array

### Environment Variables (requires "env")
- \`sdk.env.get(key)\` \u2192 Promise<string|null> \u2014 Read env variable
  - Manifest must declare \`envKeys\` array

### Secrets (requires "secrets")
- \`sdk.secrets.get(key)\` \u2192 Promise<string|null>
- \`sdk.secrets.set(key, value)\` \u2192 Promise<void>
- \`sdk.secrets.delete(key)\` \u2192 Promise<void>

### Editing (requires "editing")
- \`sdk.editing.setWidgetBounds(id, bounds)\` \u2192 Promise<void>
- \`sdk.editing.getWidgetBounds(id)\` \u2192 Promise<Bounds>
- \`sdk.editing.selectWidget(id)\` \u2192 Promise<void>

### Dataflow (requires "dataflow")
- \`sdk.emit(outputKey, value)\` \u2192 void \u2014 Emit value to connected widgets
- \`sdk.on(inputKey, cb)\` \u2192 void \u2014 Listen for values from connected widgets

### Navigation (requires "navigate")
- \`sdk.navigate.to(url)\` \u2192 void \u2014 Navigate to dimensions:// URL
- \`sdk.navigate.back()\` \u2192 void
- \`sdk.navigate.forward()\` \u2192 void

### Portal Control (requires "portal-control")
Portals are bare content WCVs — no built-in chrome. Use \`sdk.portal.*\` to build your own UI.

The \`portalId\` is the child's \`id\` from the compound manifest (e.g. \`"browser-portal"\`),
NOT the widget instance ULID. The system resolves it automatically.

**Navigation:**
- \`sdk.portal.navigate(portalId, url)\` \u2192 Promise<void>
- \`sdk.portal.goBack(portalId)\` \u2192 Promise<void>
- \`sdk.portal.goForward(portalId)\` \u2192 Promise<void>
- \`sdk.portal.reload(portalId)\` \u2192 Promise<void>
- \`sdk.portal.stop(portalId)\` \u2192 Promise<void>

**Tabs:**
- \`sdk.portal.newTab(portalId, url?)\` \u2192 Promise<{tabId}>
- \`sdk.portal.closeTab(portalId, tabId)\` \u2192 Promise<void> (can't close last tab)
- \`sdk.portal.switchTab(portalId, tabId)\` \u2192 Promise<void>

**CSS injection:**
- \`sdk.portal.injectCSS(portalId, css)\` \u2192 Promise<{key}>
- \`sdk.portal.removeCSS(portalId, key)\` \u2192 Promise<void>

**Visibility & state:**
- \`sdk.portal.setVisible(portalId, visible)\` \u2192 Promise<void>
- \`sdk.portal.getState(portalId)\` \u2192 Promise<PortalState>
- \`sdk.portal.onStateChange(portalId, cb)\` \u2192 void

**PortalState shape:**
\`\`\`typescript
{ url: string, title: string, isLoading: boolean,
  canGoBack: boolean, canGoForward: boolean, isPlayingAudio: boolean,
  activeTabId: string,
  tabs: Array<{ id, url, title, isLoading, canGoBack, canGoForward, isActive }> }
\`\`\`

### Theme (requires "theme")
- \`sdk.theme.get()\` \u2192 Promise<ThemeVars>
- \`sdk.theme.onChange(cb)\` \u2192 void

### Clipboard (requires "clipboard")
- \`sdk.clipboard.read()\` \u2192 Promise<string>
- \`sdk.clipboard.write(text)\` \u2192 Promise<void>

### Notifications (requires "notifications")
- \`sdk.notify(title, body?)\` \u2192 Promise<void>

## Widget Manifest Schema

\`\`\`json
{
  "id": "my-widget",           // human-readable type name
  "type": "custom|webportal|terminal|compound",
  "title": "Display Name",
  "capabilities": ["kv", "network", ...],
  "allowedHosts": ["api.example.com"],
  "allowedWsHosts": ["ws.example.com"],
  "envKeys": ["API_KEY"],
  "url": "https://...",        // webportal only
  "targetPortals": ["portal-id"],  // portal-control only
  "children": [                    // compound only — child widgets
    { "id": "child-portal", "type": "webportal", "url": "https://...", "layout": { "anchor": "fill" } }
  ],
  "inputs": [{ "key": "name", "type": "string", "default": "value" }],
  "outputs": [{ "key": "name", "type": "string" }],
  "props": [{ "key": "name", "type": "string|number|boolean|select", "label": "Label", "default": "value" }]
}
\`\`\`

## Compound Widgets (type: "compound")

A compound widget wraps child widgets within its bounds. The compound's \`index.html\`
renders the container UI. Child portals are positioned as WCVs by the main process.

### Step-by-step: Create a Browser Widget

**1. Create the manifest** (\`widgets/my-browser/src/widget.manifest.json\`):
\`\`\`json
{
  "id": "my-browser",
  "type": "compound",
  "title": "My Browser",
  "capabilities": ["portal-control"],
  "targetPortals": ["my-portal"],
  "children": [
    {
      "id": "my-portal",
      "type": "webportal",
      "url": "https://example.com",
      "layout": { "anchor": "fill", "top": 38 }
    }
  ]
}
\`\`\`

Key details:
- \`targetPortals\` MUST list the child IDs you want to control
- \`layout.top: 38\` reserves 38px at the top for your chrome bar — the portal fills below it
- The child \`id\` (\`"my-portal"\`) is what you pass to all \`sdk.portal.*\` calls

**2. Create the chrome UI** (\`widgets/my-browser/src/index.html\`):
\`\`\`html
<!DOCTYPE html>
<html><head><style>
  * { margin:0; box-sizing:border-box; }
  body { font-family:system-ui; background:#1e1e1e; color:#ddd; }
  .bar { display:flex; gap:4px; padding:4px 8px; height:36px; align-items:center; }
  button { background:none; border:none; color:#888; cursor:pointer; font-size:14px; }
  input { flex:1; background:#111; border:1px solid #333; border-radius:6px;
          padding:3px 10px; color:#ccc; font-size:12px; outline:none; }
</style></head>
<body>
  <div class="bar">
    <button id="back">\u2039</button>
    <button id="fwd">\u203a</button>
    <button id="reload">\u27f3</button>
    <input id="url" type="text" />
  </div>
<script>
  var P = 'my-portal'; // matches children[0].id
  function ready(fn) {
    if (window.sdk) return fn(sdk);
    var t = setInterval(function() { if (window.sdk) { clearInterval(t); fn(sdk); } }, 50);
  }
  ready(function(sdk) {
    back.onclick = function() { sdk.portal.goBack(P); };
    fwd.onclick = function() { sdk.portal.goForward(P); };
    reload.onclick = function() { sdk.portal.reload(P); };
    url.onkeydown = function(e) { if (e.key==='Enter') sdk.portal.navigate(P, url.value); };
    sdk.portal.onStateChange(P, function(s) {
      url.value = s.url;
      back.disabled = !s.canGoBack;
      fwd.disabled = !s.canGoForward;
    });
  });
</script>
</body></html>
\`\`\`

**3. Add to meta.json:**
\`\`\`json
{
  "id": "ULID_HERE",
  "widgetType": "my-browser",
  "manifestPath": "widgets/my-browser/src/widget.manifest.json",
  "bounds": { "x": 100, "y": 100, "width": 900, "height": 600 }
}
\`\`\`

The SDK is injected automatically by the builder — do NOT import it.

### Child Layout Rules

Anchored children consume space from the compound's bounds in order:
- \`{ "anchor": "top", "height": 36 }\` — fixed height strip at top
- \`{ "anchor": "bottom", "height": 50 }\` — fixed height strip at bottom
- \`{ "anchor": "left", "width": 200 }\` — fixed width strip at left
- \`{ "anchor": "right", "width": 300 }\` — fixed width strip at right
- \`{ "anchor": "fill" }\` — takes remaining space after all anchored children
- \`{ "anchor": "fill", "top": 38 }\` — fill with inset (reserves space for compound's own UI)

### Chrome-less Portal (no compound)

For a bare webpage embed with no chrome, just use a standalone \`webportal\` widget:
\`\`\`json
{ "id": "embed", "type": "webportal", "title": "Embed", "url": "https://example.com", "capabilities": [] }
\`\`\`
No compound wrapper needed. The portal renders at full widget bounds.
Control it from any other widget with \`portal-control\` capability and matching \`targetPortals\`.

## Building Widgets

- Source: \`widgets/<name>/src/index.html\` (+ optional \`.ts\`, \`.tsx\`, \`.css\`)
- esbuild compiles to \`widgets/<name>/dist/bundle.html\` on save
- SDK is injected automatically \u2014 do NOT bundle it
- Use \`window.sdk.*\` for all SDK methods

## Dataflow Wiring (connections.json)

\`\`\`json
[
  {
    "from": { "widgetId": "instance-ulid", "output": "outputKey" },
    "to": { "widgetId": "instance-ulid", "input": "inputKey" }
  }
]
\`\`\`

Widget instance IDs are ULIDs from meta.json, not the human-readable manifest IDs.

## Webportal CSS Injection (portal-rules.json)

\`\`\`json
[
  { "domain": "github.com", "css": "body { ... }", "label": "Dark mode", "enabled": true }
]
\`\`\`

Rules applied on dom-ready for matching domains. Multiple rules stack in order.

## Layout System

Scenes have two layout modes. The mode is determined by whether \`layout.html\` exists in the scene folder.

### Canvas Mode (default — no layout.html)
Widgets positioned by \`bounds\` in \`meta.json\` (absolute pixels in a design-space viewport).

**Viewport** — set in \`meta.json\`:
\`\`\`json
{ "viewport": { "width": 1920, "height": 1080 } }
\`\`\`

- **Fit mode** (default): scene scales proportionally to fill the window, centered
- **Original mode**: 1:1 pixels, scroll if viewport exceeds window
- Zoom: Cmd+/-, Cmd+0, or pinch-to-zoom
- Two-finger scroll pans the canvas

**Adding a widget in Canvas mode:**
\`\`\`json
{
  "id": "ULID",
  "widgetType": "my-widget",
  "manifestPath": "widgets/my-widget/src/widget.manifest.json",
  "bounds": { "x": 100, "y": 100, "width": 400, "height": 300 }
}
\`\`\`
Drag and resize in edit mode. Bounds are in viewport design pixels.

### Layout Mode (layout.html exists)
Create \`layout.html\` for full CSS control. Widgets placed via custom element:

\`\`\`html
<!-- Flexbox example -->
<div style="display:flex; gap:16px; padding:16px; height:100vh;">
  <dimensions-widget name="clock-widget" style="flex:0 0 200px;"></dimensions-widget>
  <dimensions-widget name="note-card" style="flex:1;"></dimensions-widget>
</div>
\`\`\`

\`\`\`html
<!-- Grid example -->
<div style="display:grid; grid-template-columns:1fr 1fr; gap:16px; padding:16px; height:100vh;">
  <dimensions-widget name="my-widget" style="grid-column:span 2;"></dimensions-widget>
  <dimensions-widget name="color-box"></dimensions-widget>
  <dimensions-widget name="note-card"></dimensions-widget>
</div>
\`\`\`

- \`name\` matches the widget's manifest \`id\` (e.g. \`"clock-widget"\`)
- Full CSS freedom: flexbox, grid, percentages, \`vh\`/\`vw\`, media queries
- \`bounds\` in meta.json is optional in Layout mode — CSS drives positioning
- Multiple \`<dimensions-widget name="same-type">\` matched by order against meta.json entries
- Compound widgets work in layout mode too: \`<dimensions-widget name="my-browser">\`
- Edit mode: click to select widgets, no drag handles (edit \`layout.html\` instead)

### Switching Modes
- **Canvas \u2192 Layout:** Create \`layout.html\` in the scene folder — auto-reloads
- **Layout \u2192 Canvas:** Delete \`layout.html\` — reverts to Canvas with last-known bounds
- Hot reload: editing \`layout.html\` triggers automatic scene reload
`
}

/**
 * Write the agent context content to all supported AI tool files.
 * Call this instead of writing to a single file — all tools get the same content.
 */
export function writeAgentContextFiles(scene: SceneState): void {
  const content = generateAgentContextContent(scene)
  for (const filename of AGENT_CONTEXT_FILES) {
    fs.writeFileSync(path.join(scene.path, filename), content, 'utf-8')
  }
}
