import fs from 'fs'
import path from 'path'
import type { SceneState } from './scene-manager'

/**
 * Generate a CLAUDE.md context file in a scene folder.
 * Claude Code reads this automatically for project context.
 */
export function generateClaudeMd(scene: SceneState): void {
  const widgetLines: string[] = []
  for (const entry of scene.meta.widgets) {
    const widget = scene.widgets.get(entry.id)
    if (!widget) continue
    const bounds = entry.bounds
    const boundsStr = bounds
      ? `at (${bounds.x}, ${bounds.y}) ${bounds.width}\u00d7${bounds.height}`
      : '(no bounds — positioned by layout.html)'
    const caps = widget.manifest.capabilities.length > 0
      ? widget.manifest.capabilities.join(', ')
      : 'none'
    widgetLines.push(
      `- **${widget.manifest.title}** (\`${entry.id}\`, type: ${widget.manifest.type}) ${boundsStr}\n  - Capabilities: ${caps}`,
    )
  }

  const widgetsSection = widgetLines.length > 0
    ? widgetLines.join('\n')
    : '_No widgets in this scene._'

  // Build dimension context section if the scene is part of a dimension
  let dimensionSection = ''
  if (scene.dimensionMeta) {
    const currentIndex = scene.dimensionMeta.scenes.indexOf(scene.slug)
    const sceneOrder = scene.dimensionMeta.scenes.join(' \u2192 ')
    dimensionSection = `
## Dimension: ${scene.dimensionMeta.title}
This scene is part of the "${scene.dimensionMeta.title}" dimension.
Scene order: ${sceneOrder}
Current position: ${currentIndex + 1} of ${scene.dimensionMeta.scenes.length}
`
  }

  // Layout mode section
  const viewport = scene.meta.viewport
  const viewportStr = viewport ? `${viewport.width}×${viewport.height}` : '1920×1080 (default)'
  let layoutSection = ''
  if (scene.layoutMode === 'layout') {
    layoutSection = `
## Layout Mode: CSS Layout
This scene uses **Layout mode** — widgets are positioned by \`layout.html\`, not by bounds in \`meta.json\`.
- Edit \`layout.html\` to change widget positioning (flexbox, grid, percentages, media queries)
- Use \`<dimensions-widget name="widget-type">\` to place widgets
- Widget bounds in meta.json are optional (CSS drives positioning)
- Drag/resize handles are disabled — edit layout.html directly
`
  } else {
    layoutSection = `
## Layout Mode: Canvas
This scene uses **Canvas mode** — widgets are positioned by \`bounds\` in \`meta.json\`.
**Viewport:** ${viewportStr} (design resolution)
**Scale modes:** Fit (scales to fill window) or Original (1:1 pixels, scroll if needed)
- Drag and resize widgets in edit mode
- To switch to CSS Layout mode, create a \`layout.html\` file in the scene folder
`
  }

  const content = `# Dimensions Scene Context

## Scene: ${scene.meta.title}
**ID:** ${scene.id}
**Slug:** ${scene.slug}
**Path:** ${scene.path}
${dimensionSection}${layoutSection}
### Active Widgets
${widgetsSection}

## IMPORTANT: What Files to Edit

**DO edit:**
- \`meta.json\` — scene title, theme (background, accent), viewport, widget layout/bounds
- \`layout.html\` — CSS layout template (Layout mode only; create to switch from Canvas to Layout)
- \`widgets/<name>/src/index.html\` — widget source code (HTML/JS/CSS)
- \`widgets/<name>/src/index.ts\` — widget TypeScript source
- \`widgets/<name>/src/widget.manifest.json\` — widget capabilities, inputs, outputs
- \`connections.json\` — dataflow wiring between widgets
- \`widgets/<portal>/portal-rules.json\` — CSS injection rules for webportals

**DO NOT edit:**
- \`.scene-runtime.html\` — AUTO-GENERATED, overwritten on every scene load and widget build
- \`widgets/<name>/dist/\` — AUTO-GENERATED by esbuild from src/
- \`CLAUDE.md\` — AUTO-GENERATED context file (this file)

### Changing the Scene Background
Every scene has a \`_background\` widget at \`widgets/_background/src/index.html\`.
This is a full-screen widget that renders behind all other widgets.

**To change the background:** Edit \`widgets/_background/src/index.html\`.
- Simple solid color: set \`body { background: #1a1a2e; }\`
- Gradient: \`body { background: linear-gradient(135deg, #0a0a0a, #1a1a2e); }\`
- Animation: use CSS \`@keyframes\` to cycle colors, pulse, etc.
- Canvas/WebGL: add a \`<canvas>\` and draw whatever you want
- Video: use a \`<video>\` element with \`object-fit: cover\`

The \`_background\` widget is a regular widget — it has full SDK access and can declare
any capabilities in its manifest (network, kv, theme, etc.). Use it for live data
backgrounds, interactive canvases, or anything else. It auto-reloads on save.

**Do NOT** edit \`.scene-runtime.html\` to change the background — it's auto-generated.

The \`theme.background\` in \`meta.json\` is a fallback color shown while widgets load.

## @dimensions/sdk API Reference

The SDK is automatically injected into every custom widget. Access it via \`window.sdk\`.

### Always Available (no capability required)
- \`sdk.scene.id()\` \u2192 string \u2014 Current scene ID
- \`sdk.scene.title()\` \u2192 string \u2014 Current scene title

### Key-Value Storage (requires "kv")
- \`sdk.kv.get(key)\` \u2192 Promise<any> \u2014 Get value by key
- \`sdk.kv.set(key, value)\` \u2192 Promise<void> \u2014 Set value (JSON serialized, max 10MB)
- \`sdk.kv.delete(key)\` \u2192 Promise<void> \u2014 Delete key
- \`sdk.kv.list(prefix?)\` \u2192 Promise<string[]> \u2014 List keys matching prefix

### Assets (requires "assets")
- \`sdk.assets.upload(file)\` \u2192 Promise<string> \u2014 Upload file, returns dimensions-asset:// URL
- \`sdk.assets.resolve(url)\` \u2192 Promise<string> \u2014 Validate and resolve asset URL
- \`sdk.assets.list()\` \u2192 Promise<AssetInfo[]> \u2014 List widget assets

### Network (requires "network")
- \`sdk.fetch(url, options?)\` \u2192 Promise<{status, headers, body}> \u2014 Proxied HTTP request (no CORS)
  - Manifest must declare \`allowedHosts\` array

### WebSocket (requires "websocket")
- \`sdk.ws.connect(url)\` \u2192 Promise<connectionId> \u2014 Open WebSocket connection
  - Manifest must declare \`allowedWsHosts\` array

### Environment Variables (requires "env")
- \`sdk.env.get(key)\` \u2192 Promise<string|null> \u2014 Read env variable
  - Manifest must declare \`envKeys\` array

### Secrets (requires "secrets")
- \`sdk.secrets.get(key)\` \u2192 Promise<string|null>
- \`sdk.secrets.set(key, value)\` \u2192 Promise<void>
- \`sdk.secrets.delete(key)\` \u2192 Promise<void>

### Editing (requires "editing")
- \`sdk.editing.setWidgetBounds(id, bounds)\` \u2192 Promise<void>
- \`sdk.editing.getWidgetBounds(id)\` \u2192 Promise<Bounds>
- \`sdk.editing.selectWidget(id)\` \u2192 Promise<void>

### Dataflow (requires "dataflow")
- \`sdk.emit(outputKey, value)\` \u2192 void \u2014 Emit value to connected widgets
- \`sdk.on(inputKey, cb)\` \u2192 void \u2014 Listen for values from connected widgets

### Navigation (requires "navigate")
- \`sdk.navigate.to(url)\` \u2192 void \u2014 Navigate to dimensions:// URL
- \`sdk.navigate.back()\` \u2192 void
- \`sdk.navigate.forward()\` \u2192 void

### Portal Control (requires "portal-control")
- \`sdk.portal.navigate(portalId, url)\` \u2192 Promise<void>
- \`sdk.portal.injectCSS(portalId, css)\` \u2192 Promise<void>
- \`sdk.portal.removeCSS(portalId, key)\` \u2192 Promise<void>
- \`sdk.portal.newTab(portalId, url?)\` \u2192 Promise<string>
- \`sdk.portal.closeTab(portalId, tabId)\` \u2192 Promise<void>
- \`sdk.portal.switchTab(portalId, tabId)\` \u2192 Promise<void>
- \`sdk.portal.getState(portalId)\` \u2192 Promise<PortalState>

### Theme (requires "theme")
- \`sdk.theme.get()\` \u2192 Promise<ThemeVars>
- \`sdk.theme.onChange(cb)\` \u2192 void

### Clipboard (requires "clipboard")
- \`sdk.clipboard.read()\` \u2192 Promise<string>
- \`sdk.clipboard.write(text)\` \u2192 Promise<void>

### Notifications (requires "notifications")
- \`sdk.notify(title, body?)\` \u2192 Promise<void>

## Widget Manifest Schema

\`\`\`json
{
  "id": "my-widget",           // human-readable type name
  "type": "custom|webportal|terminal",
  "title": "Display Name",
  "capabilities": ["kv", "network", ...],
  "allowedHosts": ["api.example.com"],
  "allowedWsHosts": ["ws.example.com"],
  "envKeys": ["API_KEY"],
  "url": "https://...",        // webportal only
  "targetPortals": ["portal-id"],  // portal-control only
  "inputs": [{ "key": "name", "type": "string", "default": "value" }],
  "outputs": [{ "key": "name", "type": "string" }],
  "props": [{ "key": "name", "type": "string|number|boolean|select", "label": "Label", "default": "value" }]
}
\`\`\`

## Building Widgets

- Source: \`widgets/<name>/src/index.html\` (+ optional \`.ts\`, \`.tsx\`, \`.css\`)
- esbuild compiles to \`widgets/<name>/dist/bundle.html\` on save
- SDK is injected automatically \u2014 do NOT bundle it
- Use \`window.sdk.*\` for all SDK methods

## Dataflow Wiring (connections.json)

\`\`\`json
[
  {
    "from": { "widgetId": "instance-ulid", "output": "outputKey" },
    "to": { "widgetId": "instance-ulid", "input": "inputKey" }
  }
]
\`\`\`

Widget instance IDs are ULIDs from meta.json, not the human-readable manifest IDs.

## Webportal CSS Injection (portal-rules.json)

\`\`\`json
[
  { "domain": "github.com", "css": "body { ... }", "label": "Dark mode", "enabled": true }
]
\`\`\`

Rules applied on dom-ready for matching domains. Multiple rules stack in order.

## Layout Mode Reference

### Canvas Mode (default — no layout.html)
- Widgets positioned by \`bounds\` in \`meta.json\` (absolute pixels in design space)
- \`viewport\` in \`meta.json\` defines design resolution (default: 1920×1080)
- Scene scales to fit available space (Fit mode) or renders at exact pixels (Original mode)
- Zoom with Cmd+/- or Ctrl+scroll

### Layout Mode (layout.html exists)
Create \`layout.html\` in the scene folder to use CSS-driven layout:

\`\`\`html
<div style="display: grid; grid-template-columns: 1fr 1fr; gap: 16px; padding: 16px; height: 100vh;">
  <dimensions-widget name="my-widget"></dimensions-widget>
  <dimensions-widget name="another-widget"></dimensions-widget>
</div>
\`\`\`

- \`<dimensions-widget name="widget-type">\` places a widget by its type name from the manifest
- Full CSS freedom: flexbox, grid, percentages, media queries, vh/vw
- Multiple instances of the same widget type are matched by order against meta.json entries
- To switch back to Canvas mode, delete \`layout.html\`

### Switching Modes
- **Canvas → Layout:** Create \`layout.html\` in the scene folder
- **Layout → Canvas:** Delete \`layout.html\` — reverts to Canvas with last-known bounds

### Viewport (meta.json)
\`\`\`json
{
  "viewport": { "width": 1920, "height": 1080 }
}
\`\`\`
Sets the design resolution for Canvas mode. Ignored in Layout mode.
`

  const outPath = path.join(scene.path, 'CLAUDE.md')
  fs.writeFileSync(outPath, content, 'utf-8')
}
